In [7]:
import numpy as np
def vectorize(int_array: np.array)->np.array:
    return np.array([np.array(make_zeros(i)) for i in int_array])

def make_zeros(i):
    temp = np.zeros(10)
    temp[i] = 1
    return temp

In [8]:
test = vectorize(np.array([1,2,4,5,6,9,1,0]))
print(type(test))
print(test)

<class 'numpy.ndarray'>
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
