consider y(x) = (8 x, 15 x)
want to build a simple model with 1 hidden layer, to test if the model works correctly
will note work since datahandling has changed

In [12]:
# test forward
import debugger as deb
import importlib
import network0
import numpy as np
import random
importlib.reload(network0)

layers = np.array([2,3,2])
weights = [np.array([[1,1],[2,2],[3,3]]), np.array([[1,2,3],[4,5,6]])]
biases = [np.array([0,0,0]), np.array([0,0])]

model_0 = network0.network(layers=layers, weights=weights, biases=biases)

model_0.forward(np.array([10,-1.2354236]))


([array([10.       , -1.2354236]),
  array([ 8.7645764, 17.5291528, 26.2937292]),
  array([122.7040696, 280.4664448])],
 [array([10.       , -1.2354236]),
  array([ 8.7645764, 17.5291528, 26.2937292]),
  array([122.7040696, 280.4664448])])

In [7]:
# test SGD
import importlib
import network0
import numpy as np
import random
importlib.reload(network0)
#create data
random.seed(42)
np.random.seed(42)

def fill():
    x = random.random()
    return [np.array((x,x)), np.array((8*x,15*x))]

data = [fill() for x in range(0,100)]

layers = np.array([2,3,2])
net = network0.network(layers=layers, seed_value=42)
net.SGD(train_data=data, eta=0.01, epochs=1000, batch_size=10, loss_fn=network0.mean_square_error, dloss_fn=network0.dmean_square_error, seed_value=10)


z,a = net.forward(np.array((2,2)))
print(z[-1])
print(a[-1])
print(type(a))

# print(net.biases)
# print(net.weights)

[16. 30.]
[16. 30.]
<class 'list'>


In [5]:
for i in range(0, 10):
    print(net.forward(np.array([i+0.1,i+0.1]))[-1])

print(type(net.forward(np.array([1,1]))))

[array([0.1, 0.1]), array([1.84951501, 0.84729315, 0.51750065]), array([0.8, 1.5])]
[array([1.1, 1.1]), array([13.1609087 ,  5.96500586,  3.80449151]), array([ 8.8, 16.5])]
[array([2.1, 2.1]), array([24.47230238, 11.08271858,  7.09148237]), array([16.8, 31.5])]
[array([3.1, 3.1]), array([35.78369606, 16.2004313 , 10.37847323]), array([24.8, 46.5])]
[array([4.1, 4.1]), array([47.09508975, 21.31814401, 13.66546409]), array([32.8, 61.5])]
[array([5.1, 5.1]), array([58.40648343, 26.43585673, 16.95245495]), array([40.8, 76.5])]
[array([6.1, 6.1]), array([69.71787711, 31.55356945, 20.23944581]), array([48.8, 91.5])]
[array([7.1, 7.1]), array([81.0292708 , 36.67128216, 23.52643667]), array([ 56.8, 106.5])]
[array([8.1, 8.1]), array([92.34066448, 41.78899488, 26.81342753]), array([ 64.8, 121.5])]
[array([9.1, 9.1]), array([103.65205816,  46.90670759,  30.10041839]), array([ 72.8, 136.5])]
<class 'tuple'>


In [183]:
import network0
importlib.reload(network0)

layers=np.array([1,2])
test = network0.network(layers=layers, seed_value=42)

a,b = test.forward(6)
print(a)

[6, array([[2.97923465],
       [6.43627978]])]


In [220]:
np.random.rand(4)

array([0.76324059, 0.87809664, 0.41750914, 0.60557756])