In [12]:
# test forward
import debugger as deb
import importlib
import network0
import numpy as np
import random
importlib.reload(network0)

layers = np.array([2,3,2])
weights = [np.array([[1,1],[2,2],[3,3]]), np.array([[1,2,3],[4,5,6]])]
biases = [np.array([0,0,0]), np.array([0,0])]

model_0 = network0.network(layers=layers, weights=weights, biases=biases)

model_0.forward(np.array([10,-1.2354236]))


([array([10.       , -1.2354236]),
  array([ 8.7645764, 17.5291528, 26.2937292]),
  array([122.7040696, 280.4664448])],
 [array([10.       , -1.2354236]),
  array([ 8.7645764, 17.5291528, 26.2937292]),
  array([122.7040696, 280.4664448])])

In [39]:
# test backpropagation
import debugger as deb
import importlib
import network0
import numpy as np
import random
importlib.reload(network0)

layers = np.array([2,3,3,3,3,5,123,54,3])
model = network0.network(layers=layers)

print(f"weights {model.weights}")
print(f"biases {model.biases}")

model.backpropagation(np.array([2,3]),np.array([2,3,2]),network0.dmean_square_error)

weights [array([[0.60796544, 0.63948453],
       [0.33835015, 0.69967952],
       [0.49450482, 0.3499137 ]]), array([[0.66421134, 0.5222397 , 0.89045063],
       [0.3473945 , 0.25906793, 0.90192623],
       [0.73871192, 0.10810836, 0.57943058]]), array([[0.98753108, 0.86855445, 0.0784523 ],
       [0.04112866, 0.89754056, 0.3274494 ],
       [0.15294547, 0.34896913, 0.045917  ]]), array([[0.55613093, 0.05234209, 0.57900335],
       [0.01331372, 0.61885539, 0.48417951],
       [0.0331037 , 0.78673228, 0.93133996]]), array([[0.07199435, 0.15388813, 0.27384605],
       [0.42172015, 0.54296689, 0.84358398],
       [0.01609897, 0.06226921, 0.61545924],
       [0.28046546, 0.32607926, 0.87779924],
       [0.70932042, 0.12335291, 0.07038713]]), array([[0.78803179, 0.60882662, 0.67515392, 0.73086591, 0.1717526 ],
       [0.64961579, 0.04608646, 0.88669871, 0.55754992, 0.83126445],
       [0.69329715, 0.79757668, 0.54453637, 0.71550497, 0.5918589 ],
       [0.10658561, 0.24275484, 0.25095621, 0

([array([[2.58831651e+17, 3.88247477e+17],
         [1.86499284e+17, 2.79748927e+17],
         [2.81618256e+17, 4.22427385e+17]]),
  array([[8.33628229e+16, 9.45102215e+16, 5.41971275e+16],
         [1.33888195e+17, 1.51791920e+17, 8.70454636e+16],
         [3.72720009e+16, 4.22560674e+16, 2.42318496e+16]]),
  array([[1.98175873e+16, 1.31677301e+16, 1.45146830e+16],
         [3.83651621e+16, 2.54916046e+16, 2.80991907e+16],
         [2.54428933e+16, 1.69054460e+16, 1.86347372e+16]]),
  array([[4.79679854e+15, 3.01562333e+15, 1.46032685e+15],
         [3.06072076e+15, 1.92419608e+15, 9.31799128e+14],
         [9.04639410e+15, 5.68723429e+15, 2.75406442e+15]]),
  array([[1.17331505e+14, 8.31457864e+13, 1.20508779e+14],
         [4.24551626e+14, 3.00854222e+14, 4.36048253e+14],
         [1.66272816e+14, 1.17827552e+14, 1.70775394e+14],
         [3.54253163e+14, 2.51037926e+14, 3.63846146e+14],
         [2.20729171e+14, 1.56417498e+14, 2.26706397e+14]]),
  array([[2.08604995e+11, 7.5354710

In [91]:
# test batch_update
import debugger as deb
import importlib
import network0
import numpy as np
import random
importlib.reload(network0)

layers = np.array([2,3])
model = network0.network(layers=layers)

print(f"weights {model.weights}")
print(f"biases {model.biases}")

test_data = [[np.array([1,2]),np.array([1,2,3])]]
model.batch_update(train_data=test_data, eta=0.1, dloss_fn=network0.dmean_square_error)

print(f"weights {model.weights}")
print(f"biases {model.biases}")

weights [array([[0.23978911, 0.75059985],
       [0.54918974, 0.25435707],
       [0.23896704, 0.36167905]])]
biases [array([0.31228354, 0.4820585 , 0.50279728])]
weights [array([[0.16957095, 0.61016353],
       [0.57985891, 0.31569542],
       [0.34129221, 0.5663294 ]])]
biases [array([0.24206539, 0.51272768, 0.60512245])]


In [97]:
# test SGD
import importlib
import network0
import numpy as np
import random
importlib.reload(network0)
#create data
random.seed(42)
np.random.seed(42)

def fill():
    x = random.random()
    return [np.array((x,x)), np.array((x,x))]

data = [fill() for x in range(0,100)]

layers = np.array([2,2,5,2])
net = network0.network(layers=layers, seed_value=42)
net.SGD(train_data=data, eta=0.1, epochs=100, batch_size=10, loss_fn=network0.mean_square_error, dloss_fn=network0.dmean_square_error, seed_value=10)


z,a = net.forward(np.array((6,1)))
print(z[-1])
print(a[-1])

# print(net.biases)
# print(net.weights)

[array([-0.36952724, -1.12527045]), array([ 0.08655561, -0.0651921 ,  0.18639128, -0.42591014,  0.0215346 ]), array([-0.27278557, -0.36255409])]
[array([[-0.06988854,  0.50628565],
       [-0.25515188, -0.38848734]]), array([[ 0.03907993,  0.00156176],
       [-0.53930558,  0.07673731],
       [ 0.17780238,  0.15016528],
       [-0.47927306,  0.31343709],
       [ 0.22230427, -0.59205533]]), array([[-0.0628853 , -0.56656679, -0.62161543, -0.06136627, -0.31488691],
       [ 0.05559427, -0.11034427, -0.75185915, -0.27192147, -0.35265386]])]


In [56]:
np.add(np.array([ 0.27897206, -0.1661378 , -1.35751845]),np.array([0.86385041, 0.94489863, 0.10851783]))

array([ 1.14282247,  0.77876083, -1.24900062])